
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootapi
      # Créer la DB par défaut
      MYSQL_DATABASE: MyApiDB
      MYSQL_USER: adapi
      MYSQL_PASSWORD: adapipwd
    ports:
      - "3306:3306"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "3"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: rootapi
    ports:
      - "8081:80"  # accès via http://localhost:8081
    networks:
      - my_network

  app:
    build: .
    container_name: spring_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - my_network
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql_db
      DB_NAME: MyApiDB
      DB_USER: adapi
      DB_PASSWORD: adapipwd

networks:
  my_network:
    driver: bridge
    name: apinetwork

volumes:
  mysql_data:
